#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:$HOME/bin/bin:$HOME/QEMU/bin:$HOME/.gem/ruby/2.5.0/bin:$HOME/go/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/bin/lib
export EPP_UKRNAMES_URL=https://jeseeq.com

ulimit -n 65536
source <(kubectl completion zsh)

alias ag='ag --path-to-ignore ~/.ignore'
# Customize to your needs...
